### ISSUE TITLE
No issue, but looking for info

### ISSUE THREAD

**Issue by bobwing-globe** [bunnykek/WeTransferTool#2]
Trying to use to automate a file upload to weTransfer, getting and Unauthorized error. I believe that it is where auth_bearer is being set with storm_upload_token. Where does one get a token?

**Comment by bunnykek** [comment]
You will get it in the response when you do the post request to (/api/v4/transfers/link)
check: https://github.com/bunnykek/WeTransferTool/blob/96b7fcdd17aa23bf11fc4e89780c077b06cebc12/WE.py#L120-L132

**Comment by bobwing-globe** [comment]
I wrote the issue up fast and I should have clarified the error better.

I am getting a token but I am getting an 'Unauthorized' error. I am testing with a PDF file.
Here is the output when I run the code.
I thought that I could install this and just run it or am I running it wrong. Do I need to install anything else?

here is the code from the send.py file

from WE import we
wet = we()
# to upload a file/folder to the server
metadata = wet.upload('/temp', '177600.pdf', 'Test')
print(metadata)



Here is the output.


Uploading temp
Total number of files: 18

Traceback (most recent call last):
  File "C:\MyFiles\Devel\python\wetransfer\WeTransferTool-main\we-send.py", line 4, in <module>
    metadata = wet.upload('/temp', '177600.pdf', 'Test')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyFiles\Devel\python\wetransfer\WeTransferTool-main\WE.py", line 36, in upload
    return self.__process_files(files, transfer_id, path, type, auth_bearer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MyFiles\Devel\python\wetransfer\WeTransferTool-main\WE.py", line 184, in __process_files
    self.__preflight(items, auth_bearer)
  File "C:\MyFiles\Devel\python\wetransfer\WeTransferTool-main\WE.py", line 249, in __preflight
    raise Exception('enable_response_s3 error\n', response.text)
Exception: ('enable_response_s3 error\n', 'Unauthorized')

Thanks for any help you can provide.

**Comment by bunnykek** [comment]
Why you are not giving the pdf file complete path in upload() method

**Comment by bobwing-globe** [comment]
I have tried both of these syntax
metadata = wet.upload('/tmp/iplist', '/tmp/iplist', 'Test')

Uploading iplist
Traceback (most recent call last):
  File "/Users/apple/devel/python/we-send.py", line 5, in <module>
    metadata = wet.upload('/tmp/iplist', '/tmp/iplist', 'Test')
  File "/Users/apple/devel/python/WE.py", line 35, in upload
    return self.__process_files(files, transfer_id, path, type, auth_bearer)
  File "/Users/apple/devel/python/WE.py", line 183, in __process_files
    self.__preflight(items, auth_bearer)
  File "/Users/apple/devel/python/WE.py", line 248, in __preflight
    raise Exception('enable_response_s3 error\n', response.text)
Exception: ('enable_response_s3 error\n', 'Unauthorized')

metadata = wet.upload('/tmp/iplist', 'iplist', 'Test')

Uploading iplist
Traceback (most recent call last):
  File "/Users/apple/devel/python/we-send.py", line 5, in <module>
    metadata = wet.upload('/tmp/iplist', 'iplist', 'Test')
  File "/Users/apple/devel/python/WE.py", line 35, in upload
    return self.__process_files(files, transfer_id, path, type, auth_bearer)
  File "/Users/apple/devel/python/WE.py", line 183, in __process_files
    self.__preflight(items, auth_bearer)
  File "/Users/apple/devel/python/WE.py", line 248, in __preflight
    raise Exception('enable_response_s3 error\n', response.text)
Exception: ('enable_response_s3 error\n', 'Unauthorized')


Each comes back with the same error

**Comment by bunnykek** [comment]
Try uploading some kind of video or audio. I have just checked and its working fine for me.

**Comment by bobwing-globe** [comment]
Same thing, does it make a difference of my location?

**Comment by bunnykek** [comment]
Yeah location somehow could be a reason. If you could tell me your region name then i could use VPN and check it.

**Comment by bobwing-globe** [comment]
I am Boston, Massachusetts, USA

**Comment by bobwing-globe** [comment]
I fired up a vpn, connected to NL and was successful in uploading and downloading files. So, being in US, must be an issue

**Comment by bunnykek** [comment]
Thanks for reporting it. I have fixed it. Now it will work irrespective of any region.
https://github.com/bunnykek/WeTransferTool/commit/b24dec740432c654529ca6fdfc6e686e77c98e37
