### ISSUE TITLE
Incorporate parallel chunks-upload 

### ISSUE THREAD

**Issue by bunnykek** [bunnykek/WeTransferTool#4]
Currently the module is uploading the chunks one-by-one. So please implement multithreading to upload the chunks simultaneously.
Implement it do a pull request.

**Comment by sculley** [comment]
Hello, please assign this issue to me.

**Comment by bunnykek** [comment]
Go on

**Comment by sculley** [comment]
@bunnykek - I have made changes to upload chunks using threads which results in faster uploads, as part of the change I want to update the command line arguments to add an option to set the max_workers to define the number of threads.

I assume you are adding the `main_module.py` and packaging for PyPy seperatly, here is the modified code that allows to pass `-mw 20` workers/threads (it defaults to 10 without this modification)

```python
import argparse
from WeTransferTool import We
import json

def main_func():
    parser = argparse.ArgumentParser()
    wet = We()

    parser.add_argument('-dl', help="Wetransfer file URL", type=str)
    parser.add_argument('-ul', help="File/Folder path", type=str)
    parser.add_argument('-mw', help="Maximum number of workers (parallel downloads)", type=int, default=10)
    args = parser.parse_args()
    dl = args.dl
    ul = args.ul
    mw = args.mw
    if not dl and not ul:
        print("Need atleast one argument. Try wetransfertool -h")
    if ul:
        print(json.dumps(wet.upload(path=ul, max_workers=mw), indent=4))
    if dl:
        wet.download(dl)
    
# if __name__=="__main__":
#     main_func()
```

**Comment by sculley** [comment]
@bunnykek - Can this be closed now?
