### ISSUE TITLE
Errors occurring when extracting metadata 

### ISSUE THREAD

**Issue by florifull** [bunnykek/WeTransferTool#6]
With the current code, there are errors occurring sometimes when extracting the "shortened_url" from our metadata. Often times, our metadata variable doesn't hold a shortened_url. This leads to errors, and takes place in the wetransfertool.py file.

Hopefully we can implement a fix.

<img width="737" alt="Screenshot 2024-09-17 at 5 36 31 PM" src="https://github.com/user-attachments/assets/2d3b3d8f-01c0-4a70-bcdc-2990de2adf13">

**Comment by bunnykek** [comment]
I will look into it.

**Comment by bunnykek** [comment]
I think you have pushed these changes in your PR. Hence closing this issue.
